### ISSUE TITLE
Persona

### ISSUE THREAD

**Issue by janviw** [UW-INFO442-AU21/group1-jeremys-goats#9]
Create 3 personas for FoodCycle users.
- Student @janviw 
- Parent @danarin 
- New Grad @lavishAl

**Comment by danarin** [comment]
Forgot I was doing the parent until I finished doing the student - sorry! Student persona is now completed and updated in the personas folder

**Comment by janviw** [comment]
I finished doing the parent persona. @danarin Do you mind pushing my persona? I need the TAs help to fix my github.

**Comment by danarin** [comment]
Updated persona 1 and added persona 2
